### This workflow will generate documentation to update the GitHub Wiki accordingly.

name: gmplot_docs

on:
  repository_dispatch:
    types: manual-docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-markdown-builder

      - name: Generate documentation
        run: |
          sphinx.cmd.build -b markdown docs docs/_build

      - name: Publish to GitHub Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          path: docs/_build
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
